package com.redridgeapps.prefs

const val PREF_IS_FIRST_RUN = "PREF_IS_FIRST_RUN"
const val PREF_RECORDING_ENABLED = "PREF_RECORDING_ENABLED"
const val PREF_RECORDINGS_STORAGE_PATH = "PREF_RECORDINGS_STORAGE_PATH"
const val PREF_AUDIO_RECORD_SAMPLE_RATE = "PREF_AUDIO_RECORD_SAMPLE_RATE"
const val PREF_AUDIO_RECORD_CHANNELS = "PREF_AUDIO_RECORD_CHANNELS"
const val PREF_AUDIO_RECORD_ENCODING = "PREF_AUDIO_RECORD_ENCODING"
const val PREF_AUTO_DELETE_ENABLED = "PREF_AUTO_DELETE_ENABLED"
const val PREF_AUTO_DELETE_AFTER_DAYS = "PREF_AUTO_DELETE_AFTER_DAYS"
