package com.redridgeapps.common.constants

const val NOTIFICATION_RECORDING_SERVICE_ID = 1
const val NOTIFICATION_MP3_CONVERSION_ONGOING_ID = 2
const val NOTIFICATION_MP3_CONVERSION_FINISHED_ID = 3
const val NOTIFICATION_WAV_TRIMMING_ONGOING_ID = 4
const val NOTIFICATION_WAV_TRIMMING_FINISHED_ID = 5
